package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Crear_seccion_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout fondoNegro;
	protected Button botonGuardarSeccion;
	protected TextField tituloSeccion;
	protected Label labelCrearSeccion;
	protected TextField iconoSeccion;
	protected CheckBox fijarSeccion;

	public Crear_seccion_Ventana() {
		Design.read(this);
	}
}
