package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensajes_Administrador_Ventana extends Panel {
	protected VerticalLayout cajaMensaje1;
	protected Image fotoUsuario1;
	protected Label nombreUsuarios1;
	protected Label fechaMensajeUsuario21313;
	protected Label descripcion1;
	protected Label temaMensaje251313;
	protected VerticalLayout cajaMensaje2;
	protected Image fotoUsuario2;
	protected Label nombreUsuarios2;
	protected Label fechaMensajeUsuario21314;
	protected Label descripcion2;
	protected Label temaMensaje2513131;

	public Mensajes_Administrador_Ventana() {
		Design.read(this);
	}
}
