package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_propietario_Ventana extends HorizontalLayout {
	protected Label citado;
	protected Button botonOcultar;
	protected Button botonEliminar;
	protected Image fotoPerfil;
	protected Button nickUsuario;
	protected Button reportar;
	protected Button botonBanear;
	protected Button botonNotificar;
	protected Label citarMen;
	protected Label mensaje;
	protected HorizontalLayout videos;
	protected Link linkVideo;
	protected HorizontalLayout imagen;
	protected Image imagen1;
	protected Image imagen2;
	protected Image imagen3;
	protected Label cantidadMeGusta;
	protected Button botonMeGusta;
	protected Button responderMensaje;

	public Mensaje_propietario_Ventana() {
		Design.read(this);
	}
}
