package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensaje_propietario_Ventana extends VerticalLayout {
	protected Image fotoUsuario1;
	protected Label nombreUsuarios1;
	protected Label fechaMensajeUsuario21313;
	protected Label descripcion1;
	protected Label temaMensaje251313;

	public Mensaje_propietario_Ventana() {
		Design.read(this);
	}
}
