package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensajes_usuario_Ventana extends Panel {
	protected HorizontalLayout cajaMensaje;
	protected Image imagenTema;
	protected Label mensaje;
	protected Label temaMensaje;
	protected Label fechaMensajeUsuario;
	protected Link eliminarMensaje6;
	protected HorizontalLayout cajaMensaje1;
	protected Image imagenTema1;
	protected Label mensaje1;
	protected Label temaMensaje1;
	protected Label fechaMensajeUsuario1;
	protected Link eliminarMensaje5;
	protected HorizontalLayout cajaMensaje11;
	protected Image imagenTema11;
	protected Label mensaje11;
	protected Label temaMensaje11;
	protected Label fechaMensajeUsuario11;
	protected Link eliminarMensaje4;
	protected HorizontalLayout cajaMensaje12;
	protected Image imagenTema12;
	protected Label mensaje12;
	protected Label temaMensaje12;
	protected Label fechaMensajeUsuario12;
	protected Link eliminarMensaje3;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected Label temaMensaje13;
	protected Label fechaMensajeUsuario13;
	protected Link eliminarMensaje2;

	public Mensajes_usuario_Ventana() {
		Design.read(this);
	}
}
