package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.VerticalLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mis_mensajes_Ventana extends Panel {
	protected VerticalLayout misMensajes;
	protected HorizontalLayout cajaMensaje;
	protected Image imagenTema;
	protected Label mensaje;
	protected Label temaMensaje;
	protected Label fechaMensajeUsuario;
	protected Link eliminarMensaje14;
	protected HorizontalLayout cajaMensaje1;
	protected Image imagenTema1;
	protected Label mensaje1;
	protected Label temaMensaje1;
	protected Label fechaMensajeUsuario1;
	protected Link eliminarMensaje13;
	protected HorizontalLayout cajaMensaje11;
	protected Image imagenTema11;
	protected Label mensaje11;
	protected Label temaMensaje11;
	protected Label fechaMensajeUsuario11;
	protected Link eliminarMensaje12;
	protected HorizontalLayout cajaMensaje12;
	protected Image imagenTema12;
	protected Label mensaje12;
	protected Label temaMensaje12;
	protected Label fechaMensajeUsuario12;
	protected Link eliminarMensaje11;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected Label temaMensaje13;
	protected Label fechaMensajeUsuario13;
	protected Link eliminarMensaje1;
	protected HorizontalLayout cajaMensaje15;
	protected Image imagenTema15;
	protected Label mensaje15;
	protected Label temaMensaje15;
	protected Label fechaMensajeUsuario15;
	protected Link eliminarMensaje;
	protected HorizontalLayout cajaMensaje2;
	protected Image imagenTema2;
	protected Label mensaje2;
	protected Label temaMensaje2;
	protected Label fechaMensajeUsuario2;
	protected Link eliminarMensaje141;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label mensaje3;
	protected Label temaMensaje3;
	protected Label fechaMensajeUsuario3;
	protected Link eliminarMensaje142;
	protected HorizontalLayout cajaMensaje4;
	protected Image imagenTema4;
	protected Label mensaje4;
	protected Label temaMensaje4;
	protected Label fechaMensajeUsuario4;
	protected Link eliminarMensaje143;
	protected HorizontalLayout cajaMensaje5;
	protected Image imagenTema5;
	protected Label mensaje5;
	protected Label temaMensaje5;
	protected Label fechaMensajeUsuario5;
	protected Link eliminarMensaje144;

	public Mis_mensajes_Ventana() {
		Design.read(this);
	}
}
