package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Moderadores_Ventana extends Panel {
	protected VerticalLayout controlModeradores;
	protected HorizontalLayout cajaModerador;
	protected Image imagenTema2;
	protected Label nombreUsuario;
	protected Link eliminarMensaje141;
	protected HorizontalLayout cajaModerador1;
	protected Image imagenTema21;
	protected Label nombreUsuario1;
	protected Link eliminarMensaje1411;

	public Moderadores_Ventana() {
		Design.read(this);
	}
}
