package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Notificaciones_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Label nombreForo;
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Link menuMiPerfilAdministrador;
	protected Link menuCerrarSesionAdministrador;
	protected Link menuNotificacionesAdministrador;
	protected Image menuimagenPerfilAdministador;
	protected Link menuPanelControlAdministrador;
	protected AbsoluteLayout fondoNegro;
	protected AbsoluteLayout cajaNotificacion;
	protected Button cerrarNotificaciones;
	protected Panel panelNotificaciones;
	protected HorizontalLayout cajaAmigos1;
	protected Image imagenUsuario31;
	protected Label nombreUsuario1;
	protected Link aceptarSolicitud;
	protected Link eliminarSolicitud;
	protected HorizontalLayout cajaAmigos11;
	protected Image imagenUsuario311;
	protected Label nombreUsuario11;
	protected Link eliminarSolicitud1;
	protected HorizontalLayout cajaAmigos12;
	protected Image imagenUsuario312;
	protected Label nombreUsuario12;
	protected Link aceptarSolicitud2;
	protected Link eliminarSolicitud2;

	public Notificaciones_Ventana() {
		Design.read(this);
	}
}
