package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Notificar_usuario_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout fondoNegro;
	protected AbsoluteLayout cajaNotificarUsuario;
	protected Label tituloMensajeBanear;
	protected Button botonCancelarNotificacion;
	protected Button botonNotificar;
	protected TextArea motivoNotificacion;

	public Notificar_usuario_Ventana() {
		Design.read(this);
	}
}
