package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Panel_de_control_ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Button menuMiPerfilAdministrador;
	protected Button menuCerrarSesionAdministrador;
	protected Button menuNotificacionesAdministrador;
	protected Button menuPanelControlAdministrador;
	protected Button nombreForo;
	protected Label tituloMensajesdeUsuario;
	protected Label tituloModeradores;
	protected Label tituloTemas;
	protected Label tituloMensajes;
	protected Label tituloNotificados;
	protected VerticalLayout paneldeControl;
	protected Button moderadores;
	protected Button temaOculto;
	protected Button mensajeOculto;
	protected Button usuarioNotificado;
	protected Button tickets;
	protected Button gestionPublicidad;
	protected Panel panelModeradores;
	protected VerticalLayout verticalModeradores;
	protected Panel panelTemasOcultos;
	protected VerticalLayout verticalTemasOcultos;
	protected Panel panelMensajesOcultos;
	protected VerticalLayout verticalMensajesOcultos;
	protected Panel panelUsuariosNotificados;
	protected VerticalLayout verticalUsuariosNotificados;

	public Panel_de_control_ventana() {
		Design.read(this);
	}
}
