package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Panel_de_control_del_moderador_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Label nombreForo;
	protected AbsoluteLayout menuUsuarioModerador;
	protected Link menuMiPerfilModerador;
	protected Link menuCerrarSesionModerador;
	protected Link menuNotificacionesModerador;
	protected Image menuimagenPerfilModerador;
	protected Link menuPanelControlModerador;
	protected Label tituloMensajesdeUsuario;
	protected Label tituloReporteMensajes;
	protected Panel panelReportes;
	protected VerticalLayout controlMensajesReportados;
	protected VerticalLayout mensajeReportado;
	protected HorizontalLayout cajaNotificado;
	protected Image imagenUsuario;
	protected Label nombreUsuario2;
	protected Link eliminarReporte;
	protected Link notificarUsuario;
	protected HorizontalLayout cajaNotificado3;
	protected Label motivo3;
	protected VerticalLayout mensajeReportado1;
	protected HorizontalLayout cajaNotificado1;
	protected Image imagenUsuario1;
	protected Label nombreUsuario21;
	protected Link eliminarReporte1;
	protected Link notificarUsuario1;
	protected HorizontalLayout cajaNotificado31;
	protected Label motivo31;
	protected VerticalLayout mensajeReportado2;
	protected HorizontalLayout cajaNotificado2;
	protected Image imagenUsuario2;
	protected Label nombreUsuario22;
	protected Link eliminarReporte2;
	protected Link notificarUsuario2;
	protected HorizontalLayout cajaNotificado32;
	protected Label motivo32;

	public Panel_de_control_del_moderador_Ventana() {
		Design.read(this);
	}
}
