package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrarse_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Label nombreForo;
	protected AbsoluteLayout menuUsuarioNoIdentifado;
	protected Link menuRegistrarse;
	protected Link menuIniciarSesion;
	protected AbsoluteLayout cajaCambiar;
	protected PasswordField campoPassword;
	protected Button botonRegistrarse;
	protected TextField campoNombreUsuario;
	protected TextField campoCorreoUsuario;
	protected PasswordField campoPassworddos;
	protected TextField campoNombreCompleto;
	protected TextField campoDescripcion;
	protected TextField campoFoto;
	protected Label cambiarcontrasena;
	protected Label errorMensaje;

	public Registrarse_Ventana() {
		Design.read(this);
	}
}
