package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Seccion_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Button nombreForo;
	protected AbsoluteLayout menuUsuarioNoIdentifado;
	protected Button menuRegistrarse;
	protected Button menuIniciarSesion;
	protected AbsoluteLayout menuUsuarioIdentificado;
	protected Button menuMiPerfilUsuario;
	protected Button menuCerrarSesionUsuario;
	protected Button menuNotificacionesUsuario;
	protected AbsoluteLayout menuUsuarioModerador;
	protected Button menuMiPerfilModerador;
	protected Button menuCerrarSesionModerador;
	protected Button menuNotificacionesModerador;
	protected Button menuPanelControlModerador;
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Button menuMiPerfilAdministrador;
	protected Button menuCerrarSesionAdministrador;
	protected Button menuNotificacionesAdministrador;
	protected Button menuPanelControlAdministrador;
	protected Label seccionesFijas;
	protected Label ultimasSecciones;
	protected Panel panelUltimasSecciones;
	protected VerticalLayout verticalUltimasSecciones;
	protected VerticalLayout verticalSeccionesFijas;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label mensaje112;
	protected HorizontalLayout cajaMensaje131;
	protected Image imagenTema131;
	protected Label mensaje131;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label mensaje132;
	protected HorizontalLayout cajaMensaje133;
	protected Image imagenTema133;
	protected Label mensaje133;
	protected Button crearSeccion;

	public Seccion_Ventana() {
		Design.read(this);
	}
}
