package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Temas_Ocultos_Ventana extends Panel {
	protected VerticalLayout controlTemasOcultos;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label temaMensaje3;
	protected Label fechaMensajeUsuario3;
	protected Link eliminarMensaje142;
	protected HorizontalLayout cajaMensaje16;
	protected Image imagenTema16;
	protected Label temaMensaje16;
	protected Label fechaMensajeUsuario16;
	protected Link eliminarMensaje132;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label temaMensaje112;
	protected Label fechaMensajeUsuario112;
	protected Link eliminarMensaje122;
	protected HorizontalLayout cajaMensaje122;
	protected Image imagenTema122;
	protected Label temaMensaje122;
	protected Label fechaMensajeUsuario122;
	protected Link eliminarMensaje112;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label temaMensaje132;
	protected Label fechaMensajeUsuario132;
	protected Link eliminarMensaje16;
	protected HorizontalLayout cajaMensaje152;
	protected Image imagenTema152;
	protected Label temaMensaje152;
	protected Label fechaMensajeUsuario152;
	protected Link eliminarMensaje3;

	public Temas_Ocultos_Ventana() {
		Design.read(this);
	}
}
