package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuario_reportado_Ventana extends VerticalLayout {
	protected HorizontalLayout cajaNotificado;
	protected Image imagenUsuario;
	protected Label nombreUsuario2;
	protected Link eliminarReporte;
	protected Link notificarUsuario;
	protected HorizontalLayout cajaNotificado3;
	protected Label motivo3;

	public Usuario_reportado_Ventana() {
		Design.read(this);
	}
}
