package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuarios_notificados_Ventana extends Panel {
	protected VerticalLayout controlNotificados;
	protected HorizontalLayout cajaNotificado;
	protected Image imagenUsuario;
	protected Label nombreUsuario2;
	protected Label motivo;
	protected Link banearUsuario;
	protected HorizontalLayout cajaNotificado1;
	protected Image imagenUsuario1;
	protected Label nombreUsuario21;
	protected Label motivo1;
	protected Link banearUsuario1;
	protected HorizontalLayout cajaNotificado2;
	protected Image imagenUsuario2;
	protected Label nombreUsuario22;
	protected Label motivo2;
	protected Link banearUsuario2;

	public Usuarios_notificados_Ventana() {
		Design.read(this);
	}
}
