package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_tema_y_mensajes_Administrador_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Label nombreForo;
	protected AbsoluteLayout menuUsuarioNoIdentifado;
	protected Link menuRegistrarse;
	protected Link menuIniciarSesion;
	protected AbsoluteLayout menuUsuarioIdentificado;
	protected Link menuMiPerfilUsuario;
	protected Link menuCerrarSesionUsuario;
	protected Link menuNotificacionesUsuario;
	protected Image menuimagenPerfilUsuario;
	protected AbsoluteLayout menuUsuarioModerador;
	protected Link menuMiPerfilModerador;
	protected Link menuCerrarSesionModerador;
	protected Link menuNotificacionesModerador;
	protected Image menuimagenPerfilModerador;
	protected Link menuPanelControlModerador;
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Link menuMiPerfilAdministrador;
	protected Link menuCerrarSesionAdministrador;
	protected Link menuNotificacionesAdministrador;
	protected Image menuimagenPerfilAdministador;
	protected Link menuPanelControlAdministrador;
	protected Label tituloTema;
	protected Panel panelMensajes;
	protected VerticalLayout cajaMensaje1;
	protected Image fotoUsuario1;
	protected Label nombreUsuarios1;
	protected Label fechaMensajeUsuario21313;
	protected Label descripcion1;
	protected Label temaMensaje251313;
	protected VerticalLayout cajaMensaje2;
	protected Image fotoUsuario2;
	protected Label nombreUsuarios2;
	protected Label fechaMensajeUsuario21314;
	protected Label descripcion2;
	protected Label temaMensaje2513131;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label mensaje3;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label mensaje112;
	protected HorizontalLayout cajaMensaje131;
	protected Image imagenTema131;
	protected Label mensaje131;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label mensaje132;
	protected HorizontalLayout cajaMensaje133;
	protected Image imagenTema133;
	protected Label mensaje133;
	protected Label seccionesDestacadas;
	protected Image anuncio;
	protected AbsoluteLayout cajaTema;
	protected Image fotoPerfil;
	protected Label nombreUsuario;
	protected Label tituloTema2;
	protected Label fechaTema;
	protected Label numeroMensajes;
	protected Image iconoMensajes;
	protected Button eliminarTema;
	protected CheckBox ponerPrivadoTema;
	protected Label descripcionTema;
	protected Button responderTema;
	protected Label numeroMeGusta;
	protected CheckBox darMeGusta;
	protected Button banearUsuarioTema;
	protected Link escribirMensaje;

	public Visualizar_tema_y_mensajes_Administrador_Ventana() {
		Design.read(this);
	}
}
