package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.Label;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_tema_y_mensajes_Ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected Label nombreForo;
	protected AbsoluteLayout menuUsuarioNoIdentifado;
	protected Link menuRegistrarse;
	protected Link menuIniciarSesion;
	protected AbsoluteLayout menuUsuarioIdentificado;
	protected Link menuMiPerfilUsuario;
	protected Link menuCerrarSesionUsuario;
	protected Link menuNotificacionesUsuario;
	protected Image menuimagenPerfilUsuario;
	protected AbsoluteLayout menuUsuarioModerador;
	protected Link menuMiPerfilModerador;
	protected Link menuCerrarSesionModerador;
	protected Link menuNotificacionesModerador;
	protected Image menuimagenPerfilModerador;
	protected Link menuPanelControlModerador;
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Link menuMiPerfilAdministrador;
	protected Link menuCerrarSesionAdministrador;
	protected Link menuNotificacionesAdministrador;
	protected Image menuimagenPerfilAdministador;
	protected Link menuPanelControlAdministrador;
	protected AbsoluteLayout cajaMensaje;
	protected Image fotoUsuario;
	protected Label nombreUsuarios;
	protected Label fechaMensajeUsuario2131;
	protected Label descripcion;
	protected Label fechaMensajeUsuario21311;
	protected Label fechaMensajeUsuario21312;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label mensaje3;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label mensaje112;
	protected HorizontalLayout cajaMensaje131;
	protected Image imagenTema131;
	protected Label mensaje131;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label mensaje132;
	protected HorizontalLayout cajaMensaje133;
	protected Image imagenTema133;
	protected Label mensaje133;
	protected Label mensaje25;
	protected Label fechaMensajeUsuario213;
	protected Label temaMensaje214;

	public Visualizar_tema_y_mensajes_Ventana() {
		Design.read(this);
	}
}
