package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_mi_perfil_ventana extends AbsoluteLayout {
	protected AbsoluteLayout menuSuperior;
	protected AbsoluteLayout menuUsuarioNoIdentifado;
	protected Button menuRegistrarse;
	protected Button menuIniciarSesion;
	protected AbsoluteLayout menuUsuarioIdentificado;
	protected Button menuMiPerfilUsuario;
	protected Button menuCerrarSesionUsuario;
	protected Button menuNotificacionesUsuario;
	protected AbsoluteLayout menuUsuarioModerador;
	protected Button menuMiPerfilModerador;
	protected Button menuCerrarSesionModerador;
	protected Button menuNotificacionesModerador;
	protected Button menuPanelControlModerador;
	protected AbsoluteLayout menuUsuarioAdministrador;
	protected Button menuMiPerfilAdministrador;
	protected Button menuCerrarSesionAdministrador;
	protected Button menuNotificacionesAdministrador;
	protected Button menuPanelControlAdministrador;
	protected Button nombreForo;
	protected AbsoluteLayout datosPerfil;
	protected Image imagenPerfil;
	protected Button cargarImagen;
	protected Label nickUsuario;
	protected TextArea descripcionUsuario;
	protected Button guardarCambios;
	protected Button listaAmigos;
	protected TextField cambiarImagen;
	protected Button listaMensajes;
	protected Label textoUltimosMensajes;
	protected VerticalLayout verticalUltimosMensajes;
	protected Button eliminarCuenta;
	protected Label tituloDatosPersonales;
	protected TextField nombreUsuarioCompleto;
	protected Button cambiarPassword;
	protected CheckBox activiarNotificaciones;
	protected CheckBox perfilOculto;
	protected Label textoMisAmigos;
	protected Panel panelAmigos;
	protected VerticalLayout verticalMisAmigos;

	public Visualizar_mi_perfil_ventana() {
		Design.read(this);
	}
}
